### ISSUE TITLE
Cоставить список статей с кратким описанием решений

### ISSUE THREAD

**Issue by light5551** [moevm/mse_indefinite_nav_ml#1]
На основе обучения с подкреплением

**Comment by didges** [comment]
[Navigating Intersections with Autonomous Vehicles using Deep Reinforcement Learning](https://medium.com/syncedreview/navigating-intersections-with-autonomous-vehicles-using-deep-reinforcement-learning-283e5fe0688f)
В этом статье рассматривают проезд перекрестка как задачу обучения с подкреплением. Они используют глубокую Q-сеть (DQN) для обучения Q-функции "состояние-действие-значение". Подход разделен на пять частей:
- Reinforcement Learning (RL)
- Q-learning.
- Dynamic Frame Skipping.
- Prioritized Experience Replay.
- State-Action Representations.
![пример](https://miro.medium.com/max/1400/0*mssS5JF2KCnCpPoh.png)
Это статья больше для будущего развития дакитауна, если в будующем планируется одновременно запускать поток машин.

**Comment by AndrewGavril** [comment]
Перенести описание в md в wiki

**Comment by AndrewGavril** [comment]
-- Список из 3-5 статей для решение end-to-end задач в сфере автопилота
-- Статьи должны быть применимы к нашей задаче: схожий input  и output
-- Описание каждого подхода из статьи с отличительными особенностями, возможно оценкой производительности
