### ISSUE TITLE
Модифакция дефолтного реварда, чтобы можно было явно указать направление.

### ISSUE THREAD

**Issue by Padalam** [moevm/mse_indefinite_nav_ml#27]
Изучение дефолтного начисления реварда, попытка выбора пунктирной линии. 

Выход -- реализация выбора конкретной пунктирной линии (например, путь налево)

**Comment by YuriyKortev** [comment]
Доп инфа: 
Обратите внимание на аргумент симулятора draw_curve, он рисует кривые для дебага.
Также обратите внимание на методы _get_curve и closest_curve_point, с ними надо работать, чтобы получить нужный результат, в зависимости от выбранного направления поворота.
