### ISSUE TITLE
Написать функцию реварда для случая перекрестка, которая учитывает направление поворота

### ISSUE THREAD

**Issue by AndrewGavril** [moevm/mse_indefinite_nav_ml#30]
Результат -- функция, которая в зависимости от направления поворота на перекрестке считает ревард от идеальной траектории (кривой базье) и реализовать wrapper одноименный

Определить всю необходимую информацию для решения задачи (использовать переменные, как будто эта информация есть)

**Comment by YuriyKortev** [comment]
Добавить к ручному проезду вывод реварда и записать видос, на котором видно, что врапер работает корректно
