### ISSUE TITLE
Написание callback'а для сохранения видео evaluation работы агента после n шагов в папку.

### ISSUE THREAD

**Issue by Gizzatovamir** [moevm/mse_indefinite_nav_ml#36]
Нужно написать callback, который будет сохранять видео, которое будет склеено из наблюдений, полученных из предсказаний (расшифровка: запустить evaluation после n шагов и сохранить видео)

**Comment by YuriyKortev** [comment]
@Crunchy0 опишу свое виденье решения

1. Унаследоваться от rlib ray.rllib.agents.DefaultCallbacks
2. Переопределить метод on_train_result
3. self.iter % self.log_rate == 0 ? идем вниз : sefl.iter++; return;
4. Получить модель можно через trainer.get_policy().model
5. Создать энвайронмент (можно через trainer.env_creator(env_config) )
6. Покрутить модель какое-то время в полученном энвайроменте, параллельно записывая видос
7. Положить полученный видос в result

Всё остальное сделает Ray и tensorboard

Чтобы tensorboard смог распознать видос, он должен иметь следующий формат: 
тип np.ndarray, ndim == 5, (1, T, C, H, W) 
T - кадры
C = 3 - каналы РГБ
H x W размер кадра

@Homry если у вас есть альтернативный вариант, то предложите Роману
